on: push
name: build website
jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.3'
    - run: flutter pub get
    #- run: flutter test
    - run: flutter build web --dart-define AWS_REGION=$(europe-west2) --dart-define IMAGE_URL=$(http://image-store-benoittemperville.com)
    # setup gcloud
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          service_account_key: $(ci-benoit-temperville-ff9ab1a9adc0)
          project_id: $(ci-benoit-temperville)
          export_default_credentials: true
    
    # Build docker image
    - name: Build docker image
      run:  docker build -t eu.gcr.io/$ci-benoit-temperville/flutterapp:$GITHUB_SHA .
    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: gcloud auth configure-docker -q

    # Push image to Google Container Registry
    - name: Push docker image to GCR
      run: docker push eu.gcr.io/$(ci-benoit-temperville)/flutterapp:$GITHUB_SHA
